### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by ricardoboss** [meilisearch/meilisearch-vue#114]
It'd be nice if we can use Typescript with this package for type safety. Currently, there are no type declaration files and the Typescript compiler throws errors because the plugin implicitly has any type.

**Comment by bidoubiwa** [comment]
Hey @ricardoboss !
`instant-meilisearch` is written in typescript and thus provides typescript support. I think you are asking for typescript support on [vue-instantsearch](https://github.com/algolia/vue-instantsearch) which is not a library we maintain. I suggest you open the issue on their repository :)

**Comment by ricardoboss** [comment]
Yeah, I think you are right. It also looks like an issue with that concern was already opened and closed without any reasoning. Thankfully, someone provided a declaration for all classes: https://github.com/algolia/vue-instantsearch/issues/378
