### ISSUE TITLE
Add Vue 3 sample to getting started code sample

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/meilisearch-vue#117]
The `getting_started_front_end_integration_md` code sample is currently only compatible with Vue 2. We should also provide code accomplishing the same thing that works with Vue 3. This code can be added within the same sample, above or below the current content.

**Comment by VoidCupboard** [comment]
Hi! Can I work on this issue?

**Comment by bidoubiwa** [comment]
The [code sample provided here](https://github.com/meilisearch/meilisearch-js/pull/1339) should be recreated but in a `html` environment and not a `.vue` one. [See example](https://github.com/meilisearch/meilisearch-vue/blob/040674f32225dbb489dea234849906ab20e31672/.code-samples.meilisearch.yaml#L41) here for vue2
