### ISSUE TITLE
Problem with ais-range-slider FACET STATS

### ISSUE THREAD

**Issue by seifrached** [meilisearch/meilisearch-vue#119]
Hi everyone,

I tried using an example that works well like [vue-instantsearch](https://vue-instantsearch.netlify.app/stories/?selectedKind=ais-range-input&selectedStory=with%20vue-slider-component&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)
from official doc [https://www.algolia.com](https://github.com/algolia/vue-instantsearch/issues/algolia.com/doc/api-reference/widgets/range-slider/vue/) but it didn't work !!!
Mainly the problem is due "RANGE" value from the slot, always 0 {range.min AND range.max} !
the minimum and maximum value is not automatically computed by Algolia from the data in the index.

```
<ais-instant-search :search-client="searchClient" index-name="NAME_OF_INDEX">


<ais-range-input attribute="area">
  <template v-slot="{ currentRefinement, range, refine, canRefine }">     
   <label>Area Range</label>     
    <vue-slider
          :min="range.min"
          :max="range.max"
          :value="toValue(currentRefinement, range)"
          :disabled="!canRefine"
          :lazy="true"
          :useKeyboard="true"
          :enableCross="false"
          tooltip="always"
          :duration="0"
          @change="refine({ min: $event[0], max: $event[1] })">
    </vue-slider>
  </template>
</ais-range-input>


</ais-instant-search>
```

BUT
Trying to use :min="0" :max="100" inside it work ≈ But the problem is that I can't retrieve any record >= to :max="100" !!!

<ais-instant-search :search-client="searchClient" index-name="NAME_OF_INDEX">

```
<ais-range-input attribute="area" :min="0" :max="100">
  <template v-slot="{ currentRefinement, range, refine, canRefine }">     
   <label>Area Range</label>     
    <vue-slider
          :min="range.min"
          :max="range.max"
          :value="toValue(currentRefinement, range)"
          :disabled="!canRefine"
          :lazy="true"
          :useKeyboard="true"
          :enableCross="false"
          tooltip="always"
          :duration="0"
          @change="refine({ min: $event[0], max: $event[1] })">
    </vue-slider>
  </template>
</ais-range-input>


</ais-instant-search>
```

```
methods:{

toValue(value, range) {
console.log(value,range)
           return [
               typeof value.min === "number" ? value.min : range.min,
               typeof value.max === "number" ? value.max : range.max,
           ];
       },
}
```

```
console.log(value)
    max: undefined
    min: undefined
=======================
console.log(range)
    max: 0
    min: 0
```

**Environment
"Laravel 8 scout",
"Vue": "^2.6.12",
"Vue-slider-component": "^3.2.20",
"@meilisearch/instant-meilisearch": "^0.7.1", AS DRIVER OF SCOUT
"algolia/algoliasearch-client-php": "^3.3",

**Comment by bidoubiwa** [comment]
Hey @seifrached, to make the range slider work with Meilisearch it requires some tweaks because indeed we do not provide the min and max values. Here is the explanation in the [instant-meilisearch readme](https://github.com/meilisearch/instant-meilisearch/#-rangeslider).

There is not really a perfect solution, if you'd like to see this implemented could you react on [the product repository](https://github.com/meilisearch/product/discussions/117)?

**Comment by seifrached** [comment]
> product

Thanks for the explanation

**Comment by bidoubiwa** [comment]
Closing as it is related to the product :)
