### ISSUE TITLE
Support for ais-numeric-menu?

### ISSUE THREAD

**Issue by henninghorn** [meilisearch/meilisearch-vue#21]
Hi!

I'm trying to figure out if the [ais-numeric-menu Vue component](https://www.algolia.com/doc/api-reference/widgets/numeric-menu/vue/) is supported or not.

Below I have the following search box, but somehow the ais-numeric-menu component doesn't seem to apply anything to the search request to Meilisearch. The request only sends `attributesToHighlight`, `facetsDistribution`, `filters`, `limit` and `q`.
- `filters` is something I have manually set in the ais-configure component to debug, see attached screenshot below

The numeric refinements are applied to the "state", but they are not applied to the search request.
Is it not supported or am I doing something wrong?

Looking forward to hear your thoughts :)

----

Vue markup:
```vue
<ais-instant-search :search-client="searchClient" index-name="movies">
    <ais-configure :filters="'release_date > 795484800'"/>
    <ais-search-box placeholder="Søg efter produkter..." show-loading-indicator/>
    <ais-state-results>
      <template slot-scope="{ state, results: { hits, query }}">
        <div v-if="hits.length > 0 && query.length > 0" style="display:flex;">
          <code>
            <pre>
                {{ JSON.stringify(state, null, 4) }}
            </pre>
        </code>
          <ais-refinement-list attribute="genres" :sortBy="sortBySettings"
            style="background-color: #ccc;padding: 1rem 1.5rem;margin-right:1rem">
            <p slot="item" slot-scope="{ item, refine }" :style="{ fontWeight: item.isRefined ? 'bold' : '' }"
              @click.prevent="refine(item.value)">
              <ais-highlight attribute="item" :hit="item" />
              ({{ item.count.toLocaleString() }})
            </p>
          </ais-refinement-list>
          <ais-numeric-menu attribute="release_date" :items="dateRanges" />
          <ais-hits>
            <div slot="item" slot-scope="{ item }" style="clear:both;padding: 1rem 0">
              <img :src="item.poster" alt="" style="width:50px;float:left">
              <div style="margin-left: 60px">
                <p v-text="item.title"></p>
                <p v-text="item.overview"></p>
              </div>
            </div>
          </ais-hits>
        </div>
        <div v-if="hits.length == 0 && query">
          No results
        </div>
        <div v-else>
          <!-- Do not display anything when query.length == 0 -->
        </div>
      </template>
    </ais-state-results>
  </ais-instant-search>
```

Screenshot of search box and network request:
![Skærmbillede 2021-03-17 kl  11 30 16](https://user-images.githubusercontent.com/742607/111453770-38626400-8714-11eb-81b1-4b03dac81763.png)

**Comment by henninghorn** [comment]
My current workaround is to proxy the search request through a custom search client, like when you're doing [conditional requests](https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/vue/).

```js
searchClient: {
  search(requests) {
    if (requests.every(({ params }) => !params.query)) {
      return Promise.resolve({
        results: requests.map(() => ({
          hits: [],
          nbHits: 0,
          nbPages: 0,
          page: 0,
          processingTimeMS: 0,
        }))
      })
    }

    requests.forEach(request => {
      if (request.params.numericFilters?.length > 0) {
        let currentFilters = request.params?.filters
        let filtersToAdd = request.params.numericFilters.join(' AND ')

        request.params.filters = [currentFilters, filtersToAdd].filter(f => f).join(' AND ')
      }
    })

    return meilisearchClient.search(requests)
  }
},
```

The above simply "moves" the numericFilters into the filters parameter :)

**Comment by bidoubiwa** [comment]
Hello @henninghorn 
I'm taking a closer look at this I will come back to you

**Comment by bidoubiwa** [comment]
Hello @henninghorn 
I have investigated and made some tests and made instant-meilisearch compatible with numeric fields. 
Here is the PR that fixes the issue: https://github.com/meilisearch/instant-meilisearch/pull/372

And here is a demo if you already want to play with it: 
[app generated by codesandbox](https://uj2tr.csb.app/)
[Codesandbox](https://codesandbox.io/s/meilisearch-boardgames-uj2tr?file=/src/App.vue)

You can see the filter that is sent to meilisearch in the console of the dev tool. 
Sorry for the delay, lots of work

**Comment by henninghorn** [comment]
Hi @bidoubiwa 

That sounds great! I appreciate your work on this.
