### ISSUE TITLE
To use meilisearch-vue in a demo project

### ISSUE THREAD

**Issue by anborg** [meilisearch/meilisearch-vue#3]
Hi 

I tried to use meilisearch-vue in a demo project

https://github.com/anborg/vue3-demo/blob/master/src/components/MeiliSearch.vue

However, the search box is not visible. Perhaps I'm missing something? Help is much appreciated.

![image](https://user-images.githubusercontent.com/56970398/91341838-22a54580-e7a8-11ea-8818-3a1d0ab1e54b.png)

The meilisearch component was imported to App.vue.
![image](https://user-images.githubusercontent.com/56970398/91342024-6e57ef00-e7a8-11ea-92d8-73ae4a4b4b68.png)

**Comment by bidoubiwa** [comment]
Hello ! 
I tried running your example but the following error was thrown: 
```bash

This dependency was not found:

* @meilisearch/instant-meilisearch in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/MeiliSearch.vue?vue&type=script&lang=js

To install it, you can run: npm install --save @meilisearch/instant-meilisearch
```

The other problem is that `instantMeiliSearch` is a default export so you should import it like this:

```javascript
import instantMeiliSearch from '@meilisearch/instant-meilisearch';
```


After all this, It indeed does not work. 
It seems that [`vue-instantsearch`](https://github.com/algolia/vue-instantsearch) - on which we depend - is not compatible with vue 3 as they use `slots`.

**Comment by anborg** [comment]
Thank you for trying. 

Is there a way to "undepend" on vue-instantsearch -- e.g removing that 'instant' functionality in melisearch-vue for a vue3 branch?

**Comment by bidoubiwa** [comment]
Unfortunately no, we heavely depend on it. We are a wrapper arround that library. Could you maybe open an issue on their repository to ask for a working exemple without `slots` because of vue 3 ?
