### ISSUE TITLE
Demo in codesandbox isn't working

### ISSUE THREAD

**Issue by fharper** [meilisearch/meilisearch-vue#6]
When you open the Nobel Prize Winners example with codesandbox, it opens with an error. I tried on macOS 11.01 build 20B29 in Google Chrome 87.0.4280.67 & Brave Browser 87.1.17.73

![](https://user-images.githubusercontent.com/1170989/100922827-58934d80-34ac-11eb-8ff9-2cb17c4a9c12.png)

**Comment by curquiza** [comment]
Hello @fharper!

The codesandbox of Vue works perfectly for me. The URL is https://1d6bi.csb.app. I tested it on Chrome, Firefox, and Safari.

**Comment by curquiza** [comment]
Pretty sure this was my fault! I fixed it! It should be ok now.

Thanks for your report @fharper! Really appreciated! :heart:
