### ISSUE TITLE
Errors not caught when the data isn't present

### ISSUE THREAD

**Issue by fharper** [meilisearch/meilisearch-vue#7]
I used the [codeandbox demo](https://codesandbox.io/s/ms-vue-is-1d6bi?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.vue), and I pointed the demo to my own MeiliSearch instance (changed the URL and token in the instance creation in Vue.js).

![image](https://user-images.githubusercontent.com/1170989/102379571-fd298b00-3f94-11eb-9a19-bbf2394c8a84.png)

I don't have the data, so the demo doesn't work obviously, but it doesn't fail gracefully. It would be nice to catch this so those error aren't return to the user, but also maybe displaying a "please add the data to your instance by doing XYZ".

![image](https://user-images.githubusercontent.com/1170989/102379953-65786c80-3f95-11eb-812e-9a1ef4162460.png)

The 7 errors after the first one are the KeyEventHandler one. I'm using latest version of Brave on latest version of macOS.

![image](https://user-images.githubusercontent.com/1170989/102379969-68735d00-3f95-11eb-8103-4fa203f300eb.png)

**Comment by fharper** [comment]
@CaroFG I already created an issue about the error management in the vue integration

**Comment by curquiza** [comment]
Related to https://github.com/meilisearch/instant-meilisearch/issues/199

**Comment by bidoubiwa** [comment]
fixed by: https://github.com/meilisearch/instant-meilisearch/pull/216
