### ISSUE TITLE
ais-sort-by is not working as expected

### ISSUE THREAD

**Issue by ntraykov** [meilisearch/meilisearch-vue#84]
`ais-sort-by`'s refine method works by generating a URL with the index containing the sort. This is because unlike Meilisearch, Algolia's sorting functionallity is working by creating a different index with the data sorted in a desired way. 

So, for example if I call `refine` with price:asc, as described in the documentation of Meilisearch like this: `refine('price:desc')`, the URL will be http://127.0.0.1:7700/indexes/price/search with post parameter sort: ['desc'].

Expected behaviour: 
- URL: http://127.0.0.1:7700/indexes/products/search (because my index is 'products');
- Post parameter: sort: ['price:desc']

**Comment by ntraykov** [comment]
By experimenting, I've found a hack that works - if I put this in the refine method: `refine('products:price:asc')`, it generates exactly what I want. It is not described in the documentation. I will write to Algolia about this.

**Comment by Sharvadze** [comment]
@ntraykov can you please share the full snippet, I'm having the same issue. Thanks inadvance

**Comment by bidoubiwa** [comment]
@Sharvadze 
This [documentation](https://github.com/meilisearch/instant-meilisearch/#-sortby) shoud answer your question. Here is a [working example](https://github.com/meilisearch/demo-MoMA/blob/ce8e21b5f5b7b4d8de2a40d070a632f5d040aa21/src/App.vue#L62).
