### ISSUE TITLE
Example of sorting 

### ISSUE THREAD

**Issue by Sharvadze** [meilisearch/meilisearch-vue#85]
Hi, I'm using the instant-search widget for my search and would like to add a default sorting to it. Can't find any resources how it can be done in Vue, an example will be greatly appreciated

**Comment by bidoubiwa** [comment]
Hello @Sharvadze 
About how to sort in vue, here is the documentation from [`instantSearch.js`](https://www.algolia.com/doc/api-reference/widgets/sort-by/vue/). 

We provide some additional customization that you can read about [here](https://github.com/meilisearch/instant-meilisearch/#-sortby).

I hope this answers your question, feel free to come back if there is any confusion

**Comment by bidoubiwa** [comment]
Here is a [working example](https://github.com/meilisearch/demo-MoMA/blob/ce8e21b5f5b7b4d8de2a40d070a632f5d040aa21/src/App.vue#L62).

**Comment by Sharvadze** [comment]
@bidoubiwa Thanks a lot!
