### ISSUE TITLE
ais-range-input is not working with meilisearch. 

### ISSUE THREAD

**Issue by ntraykov** [meilisearch/meilisearch-vue#86]
The min and max values of the range filter are always 0. I suppose it is wokring like this because Aloglia uses facets for this input while Meilisearch - filters. If I create a custom component, it won't work with the routing system.

**Comment by bidoubiwa** [comment]
Hello @ntraykov 
Unfortunately MeiliSearch does provide the `min` `max` value the widget requires to work properly. Nonetheless, you can set them manually to make the widget work. 

This is the documentation of [instantsearch.js](https://www.algolia.com/doc/api-reference/widgets/range-input/vue/) about `ais-range-input`. This is the [workaround to make the slider work](https://github.com/meilisearch/instant-meilisearch/#rangeslider) with `instant-meilisearch`.  It is the same workaround for both ais-range-input and ais-range-slider. 

I hope this answers your question. Feel free to come back if it does not!

**Comment by ntraykov** [comment]
It is working when I put random min and max values. But the problem is that when using routing when using range input, when the inputs are empty, the URL has a query param `price=0,10000`. Usually Algolia takes min and max automatically from the hits but in my case I don't have access to the hits. And also the query param is not needed if there is nothing added by the user.

**Comment by bidoubiwa** [comment]
>  Usually Algolia takes min and max automatically from the hits but in my case I don't have access to the hits. And also the query param is not needed if there is nothing added by the user.

Unfortunately, MeiliSearch does not provide a min and max. It is not possible to change the `min` `max` value dynamically :/ 
I don't see a good solution for you problem right now. You can vote [here](https://roadmap.meilisearch.com/c/119-facet-statistics) if you want it to be implemented faster in MeiliSearch!

**Comment by ntraykov** [comment]
@bidoubiwa Thanks a lot for your response! I managed to make it work. I've just put a big enough value. It is showing in the route but I don't care. It is filtering as expected. I've tried to get the intantSearchInstance from the ais-range-input but I wasn't able to fetch the hits. If I can I'll try to contribute to this as it would be useful and it is a cool feature.

**Comment by bidoubiwa** [comment]
Thanks a lot @ntraykov. I'm closing this issue as it seems resolved. Feel free to re-open if you don't feel it is! 

It would be a pleasure to have you contribute to this project :)
