### ISSUE TITLE
Problems with search, letters disappear

### ISSUE THREAD

**Issue by bmpf** [meilisearch/meilisearch-vue#94]
**Description**
When searching the first word, some letters disappear because of the high latency or big payload, is there a way of using a custom debouncer ? Or decrease the frequency of requests between typing letters.

**Screenshots or Logs**
![ezgif-2-63f0b32322](https://user-images.githubusercontent.com/33966960/149615885-f45bdcee-6c97-43f1-a19a-6d15cd620a75.gif)

**Environment (please complete the following information):**
- MeiliSearch version: v0.25.1
- instant-meilisearch version: v0.6.0
- vue-instantsearch version: v4.3.1

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/instant-meilisearch/issues/644
